name: build

on:
  repository_dispatch:
    types: [ngrok_version]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x +e
          printenv
          echo ${{ github.event.client_payload.ngrok_version }}
          echo ${{ github.event.client_payload }}
          echo ${{ github.event }}

      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push
        uses: docker/bake-action@master
        env:
          VERSION: ${{ github.event.client_payload.ngrok_version }}
        with:
          targets: |
            image-all
            image-all-slim

          push: ${{ github.event_name != 'pull_request' }}
          files: docker-bake.hcl
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
