name: build

on:
  push:
    branches:
      - "master"
      - "main"
      - "dev*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "master"
      - "main"
      - "dev*"
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1


      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push
        uses: docker/bake-action@master
        # env:
        #   VERSION: ${{ steps.vars.outputs.version }}
        with:
          targets: |
            image-all
            image-slim-all
          push: ${{ github.event_name != 'pull_request' }}
          files: docker-bake.hcl
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
